# Generated by Django 5.1.4 on 2025-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='crypto_asset',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='url',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
